### ISSUE TITLE
Addon seems to crash Players/Clients

### ISSUE THREAD

**Issue by TimeLost4** [TheNickSkater/ttt2-second_chance#5]
When second chance is bought and the player dies or at other random times the client crashes.
The outdated addon: https://steamcommunity.com/sharedfiles/filedetails/?id=672173225 still works.
If you need (and know where i can find it) I can send some logs too.
Collection used: https://steamcommunity.com/sharedfiles/filedetails/?id=2019555673

If you should need any other info let me know.

**Comment by NickCloudAT** [comment]
You are the first person to ever report something like this.. I use my own addon too and nobody on my server has ever had this problem.. Nor anybody else on the TTT2 Discord that I know of.

I can only assume that his is a gmod error, a server error or another addon is doing something wrong.. My ASC is not even doing that much that could cause a crash.. Actually, it's doing nothing that should cause a crash.
